version: "3"
services: 
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 49160:3000
    links:
      - mongo
    volumes: 
      - .:/usr/src/app
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"