version: "3"
services: 
  cb_app: 
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 49161:4000
    links:
      - cb_mongo
    volumes: 
      - .:/usr/src/app
    depends_on: 
      - cb_mongo
  cb_mongo:
    container_name: cb_mongo
    image: mongo
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"