version: "3"
services: 
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 49160:3000
    links:
      - mongo
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /data/db
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"